# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: global_gtfs_graph/graph.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'global_gtfs_graph/graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dglobal_gtfs_graph/graph.proto\"k\n\x04Stop\x12\x0f\n\x07stop_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03lat\x18\x03 \x01(\x01\x12\x0b\n\x03lon\x18\x04 \x01(\x01\x12\x19\n\x0cminutes_used\x18\x05 \x01(\x05H\x00\x88\x01\x01\x42\x0f\n\r_minutes_used\"X\n\x04Line\x12\x0f\n\x07line_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x63olor\x18\x03 \x01(\t\x12\x0f\n\x07type_id\x18\x04 \x01(\x05\x12\x11\n\tagency_id\x18\x05 \x01(\t\"Q\n\x07Journey\x12\x0f\n\x07line_id\x18\x01 \x01(\x05\x12\r\n\x05stops\x18\x02 \x03(\x05\x12\x18\n\x10times_within_day\x18\x03 \x03(\x05\x12\x0c\n\x04\x64\x61ys\x18\x04 \x03(\x05\"b\n\x04\x45\x64ge\x12\x15\n\rstart_stop_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x65nd_stop_id\x18\x02 \x01(\x05\x12\x0f\n\x07line_id\x18\x03 \x01(\x05\x12\x1d\n\x15mean_duration_minutes\x18\x04 \x01(\x02\"i\n\tFeedGraph\x12\x14\n\x05stops\x18\x01 \x03(\x0b\x32\x05.Stop\x12\x14\n\x05lines\x18\x02 \x03(\x0b\x32\x05.Line\x12\x1a\n\x08journeys\x18\x03 \x03(\x0b\x32\x08.Journey\x12\x14\n\x05\x65\x64ges\x18\x04 \x03(\x0b\x32\x05.Edgeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'global_gtfs_graph.graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOP']._serialized_start=33
  _globals['_STOP']._serialized_end=140
  _globals['_LINE']._serialized_start=142
  _globals['_LINE']._serialized_end=230
  _globals['_JOURNEY']._serialized_start=232
  _globals['_JOURNEY']._serialized_end=313
  _globals['_EDGE']._serialized_start=315
  _globals['_EDGE']._serialized_end=413
  _globals['_FEEDGRAPH']._serialized_start=415
  _globals['_FEEDGRAPH']._serialized_end=520
# @@protoc_insertion_point(module_scope)
